language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - jruby-19mode
  - rbx-19mode
env:
  - MINITEST="~>5.7.0"
  - MINITEST="~>5.6.0"
  - MINITEST="~>5.5.0"
matrix:
  allow_failures:
    - rvm: rbx-19mode
